### ISSUE TITLE
[Feature] download all pokemon on startup

### ISSUE THREAD

**Issue by Mavv3006** [Mavv3006/Pokemon-Pokedex-App#23]
**Describe the solution you'd like**
At the first start of the app all pokemons should be downloaded and inserted into the database

**Additional context**
These information should then be used to feed the list and search

**Todo**
- [x] check if the database is up to date
- [x] if not download and insert the remaining pokemon
- [x] use the data from the database to display the pokemon list on the main screen
- [x] show the user that there is a download in progress
